### ISSUE TITLE
Support /* GraphQL */

### ISSUE THREAD

**Issue by mxstbr** [jparise/vim-graphql#11]
The `language-babel` Atom plugin supports highlighting strings marked with `/* GraphQL */` as GraphQL. We use that pretty heavily, for example:

```JS
const User = /* GraphQL */`
  type User {
    id: ID!
  }
`
```

**Comment by jparise** [comment]
I thought about this a bit over the weekend, and I don't think this should be implemented at the vim-graphql level. Two reasons:

1. Unlike #8, there isn't a clearly-defined place to "attach" this functionality. To support it here, we'd need to encode quite a few JavaScript-specific syntax details just to get to the point where we can reliably identify the text region that should be highlighted as GraphQL.
2. This feels like something that should be implemented by a JavaScript-specific plugin. It could delegate syntax highlighted to plugins like vim-graphql based on the filetype named within the comments. This is conceptually similar to the way that vim-markdown handles [fenced code blocks](https://github.com/plasticboy/vim-markdown#fenced-code-block-languages).

The rationale in (2) probably applies to the ES6 template support I recently added, too. If [vim-javascript](https://github.com/pangloss/vim-javascript) adds generic support for delegated filetype highlighting, I'll probably remove it from vim-graphql.

All that being said, I'd consider a patch that adds this support, but I'm unlikely to merge it unless it's a very straightforward implementation or a large number of people really need it to work effectively with GraphQL in JavaScript (and who don't want to use something like [graphql-tag](https://github.com/apollographql/graphql-tag)).

**Comment by mxstbr** [comment]
That's fair, thanks for the thoughtful response—appreciated! :blush:
