### ISSUE TITLE
[Feature Request] Support for vim-ruby

### ISSUE THREAD

**Issue by lunks** [jparise/vim-graphql#12]
Hi, I'd like to be able to see syntax-highlighting support for ruby strings:

```
  describe 'with default arguments' do
    let(:query) do
      '
      query QueryMeals {
          meals {
             id
          }
      }
      '
    end
  end
```

This looks a bit harder as there is no convention to tag them (as opposed to javascript where usually you have `gql`/`graphql`).

**Comment by jc00ke** [comment]
You could key off a `HEREDOC` like `GRAPHQL` or `GQL`

```ruby
<<~GRAPHQL
  query QueryMeals {
    meals {
      id
    }
  }
GRAPHQL
```

**Comment by jparise** [comment]
This is similar to the proposal raised in #11, and I think I'd apply the same reasoning here.

I'm open to considering a patch for this, but I'll be weighing its inclusion based on code complexity and fragility. (Sorry to be vague in this regard; I don't know the Ruby grammar well enough to know how tricky this might be to be done well. Please educate me if this is straightforward!)

**Comment by jparise** [comment]
Closing this for now, but I'm still open to considering a patch if someone is interested in trying out some approaches.

**Comment by sodapopcan** [comment]
The RubyMine plugin uses the `<<-GRAPHQL` heredoc for this.  I wouldn't mind taking a stab at this (as I very much want it).

**Comment by jparise** [comment]
@sodapopcan That sounds good! Please read my comment in #11 before you get too far, though. I’d like to offer this functionality, but only if the implementation is straightforward, testable, and can’t be accomplished using an existing construct.
