### ISSUE TITLE
Schema-based autocomplete support

### ISSUE THREAD

**Issue by jparise** [jparise/vim-graphql#2]
Atom supports this via the [atom-graphql-autocomplete](https://github.com/nicolaslopezj/atom-graphql-autocomplete) plugin.

Consider [graphql-config](https://github.com/graphcool/graphql-config)-based endpoint configuration ([specification](https://github.com/graphcool/graphql-config/blob/master/specification.md)).

**Comment by faergeek** [comment]
Hi, I started working on plugin for deoplete, it lacks some features and code is pretty crappy for now (I'm bad at Python), but I plan to refactor it and write tests.

Here's the repo https://github.com/faergeek/deoplete-graphql

**Comment by shinzui** [comment]
It would be great for to have deoplete completion for graphql schemas.

**Comment by mekhami** [comment]
Is this on the roadmap? It'd be a huge deal for my team's workflow, for sure.

**Comment by jparise** [comment]
This is the next "big" feature I'd like to explore, but there is no timeline.

**Comment by jparise** [comment]
The [GraphQL Language Service](https://github.com/graphql/graphiql/tree/master/packages/graphql-language-service) running as a LSP server (with vim as an LSP client) feels like the modern solution to this use case.

**Comment by collegeimprovements** [comment]
[Reddit Discussion]( https://www.reddit.com/r/vim/comments/gi51hj/vim_graphql_client/ )

**Comment by felippepuhle** [comment]
I've created  [coc-graphql](https://github.com/felippepuhle/coc-graphql) if you guys want to take a look... I'm a newbie on vim/coc stuff but it's working for now!

**Comment by acao** [comment]
> The [GraphQL Language Service](https://github.com/graphql/graphiql/tree/master/packages/graphql-language-service?rgh-link-date=2019-12-16T22%3A44%3A13Z) running as a LSP server (with vim as an LSP client) feels like the modern solution to this use case.

we've had some new releases as well! more to come. check out the latest 2.5.0-alphas for graphql-config@3 support, dropping the `fb-watchman` dependency, more language features! 

for 2.5.0-alpha, just in terms of completion, we fix variable definition completion for 2.4.x where it was broken in an 2.4.0-alpha typescript conversion, and it adds named variable completion, as well

in that release, we also have added jump to workspace symbols support (might not be useful to vim users?), and we have the language server pre-cache a temporary SDL copy of the result of `projectConfig.getSchema()` for jump to definition support, etc.

**Comment by jparise** [comment]
@acao Would you be willing to contribute some documentation that explains how to set up GraphQL LSP support in vim (or point me at some existing documentation that I could link to)?

**Comment by acao** [comment]
there is an neovim? coc plugin, and any other LSP interoperable vim plugins should work

https://github.com/felippepuhle/coc-graphql

does that work for you? or are you using a different vim client? i usually just run the vanilla vim when I use it, not super familiar with neovim or other variants or vim plugin ecosystems really

**Comment by jparise** [comment]
@acao Thanks! c5169b2705f23cc4926606a7786d8e8fae138d5c adds a coc-graphql reference to `README.md`.

**Comment by jparise** [comment]
I'm going to close this issue now that there's at least one way (https://github.com/felippepuhle/coc-graphql) to enable schema-based completion.

**Comment by felippepuhle** [comment]
> I'm going to close this issue now that there's at least one way (https://github.com/felippepuhle/coc-graphql) to enable schema-based completion.

CoC provides a way to configure any language server directly on its configurations, so I decided to deprecate this package. For further instructions, please read https://github.com/neoclide/coc.nvim/wiki/Language-servers#graphql as it's a better way (you can update the LSP any time and get a better experience).

**Comment by jparise** [comment]
Thanks, @felippepuhle. I've revised the documentation in 735b93d.
