### ISSUE TITLE
ES2015 string literals not working with yajs

### ISSUE THREAD

**Issue by ghost** [jparise/vim-graphql#20]
With https://github.com/othree/yajs.vim the string literal highlighting doesn't seem to work. Removing yajs does work. Not sure if this is an issue with yajs or vim-graphql.

![screen shot 2018-11-10 at 9 02 42 am](https://user-images.githubusercontent.com/141213/48290701-e405a480-e4c7-11e8-9b37-b741a0db6508.png)

```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GE
NERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/build/config -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180820-47777-1t89t8z/neovim-
0.3.1/build/src/nvim/auto -I/tmp/neovim-20180820-47777-1t89t8z/neovim-0.3.1/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"
```

**Comment by jparise** [comment]
I've only built and tested support for [vim-javascript](https://github.com/pangloss/vim-javascript) so far. It looks like [yajs.vim](https://github.com/othree/yajs.vim) has some template tag support, but I'll need to spend some time with it in order to see if we can make it work.

I'd be happy to review a Pull Request that adds support for it. Otherwise, I'm afraid you'll need to wait until I get some time to look into it myself.

**Comment by jparise** [comment]
Something along these lines in `after/syntax/javascript/graphql.vim` appears to work:

```vim
if exists('b:current_syntax')
  let s:current_syntax = b:current_syntax
  unlet b:current_syntax
endif
syn include @GraphQLSyntax syntax/graphql.vim
if exists('s:current_syntax')
  let b:current_syntax = s:current_syntax
endif

let s:tags = '\%(' . join(g:graphql_javascript_tags, '\|') . '\)'

exec 'syntax region graphqlTemplateString start=+' . s:tags . '\@20<=`+ skip=+\\`+ end=+`+ contains=@GraphQLSyntax,graphqlTemplateExpression extend'
exec 'syntax match graphqlTaggedTemplate +' . s:tags . '\ze`+ nextgroup=graphqlTemplateString'

" Support expression interpolation ((${...})) inside template strings.
syntax region graphqlTemplateExpression start=+${+ end=+}+ contained contains=javascriptGlobal,javascriptBOMWindowProp,javascriptBOMWindowMethod,@javascriptExpression containedin=graphqlFold keepend

hi def link graphqlTemplateString javascriptTemplate
hi def link graphqlTaggedTemplate javascriptTagRef
hi def link graphqlTemplateExpression javascriptTemplateSubstitution

syn cluster javascriptTypes add=graphqlTaggedTemplate
syn cluster javascriptTypes add=graphqlTemplateString
syn cluster javascriptEventTypes add=graphqlTemplateString
syn cluster javascriptTemplates add=graphqlTemplateString
syn cluster javascriptTemplates add=graphqlTemplateExpression
syn cluster graphqlTaggedTemplate add=graphqlTemplateString
```

I'm not entirely sure how best to support this directly in vim-graphql. I think I'd need to do something where I attempt to detect which of the various JavaScript plugins were installed and customize this code accordingly.

**Comment by jparise** [comment]
Now that we have good JavaScript support "out of the box" with Vim 8.2, and we have very good support with the [vim-javascript](https://github.com/pangloss/vim-javascript) plugin, I don't think we _need_ to support any additional JavaScript plugins (such as yajs).

It wouldn't be too hard to add (given my example above), but it does complicate the testing matrix going forward, so the bar for inclusion is higher now.

I'm going to close this issue unless there's a significant need for yajs support.
