### ISSUE TITLE
Schema definition support?

### ISSUE THREAD

**Issue by vadimshvetsov** [jparise/vim-graphql#27]
Is this plugin supposed to work with schema definitions?

Let's say I have file `schema.graphql` and sketching there my schema.
```graphql
type Query {
  greetings: String
}
```

At now I have this error:
```
Parsing error: Unexpected token, expected "="
```

**Comment by jparise** [comment]
Yes, that should work just fine (and I just verified it locally). I'm not sure where that `Parsing error` is coming from, though. It doesn't look like a vim(script) error. Perhaps another plugin is interfering?

**Comment by vadimshvetsov** [comment]
Thanks for response - looks like issue on my side, I'll debug it, thank you a lot

**Comment by Lilja** [comment]
1.5 years later, I got the same error and I noticed I still had ALE enabled(switched to coc.nvim), that might be the issue for future readers.
