### ISSUE TITLE
syntax highlight not working

### ISSUE THREAD

**Issue by codeNgamer** [jparise/vim-graphql#3]
Just installed this plugin using Vundle. I've opened up several ".graphql" files now but I get no syntax highlighting.

**Comment by jparise** [comment]
@codeNgamer, could you verify the detected filetype by running `:echo &filetype`? It should print `graphql`. If it doesn't, the plugin is failing to detect the file for some reason.

**Comment by codeNgamer** [comment]
@jparise somehow it took sourcing my vimrc a couple times before it started working. I'll close this now though
