### ISSUE TITLE
Document how to configure for custom extensions?

### ISSUE THREAD

**Issue by serixscorpio** [jparise/vim-graphql#30]
Hi, thank you for making this plugin.  I appreciate it!

I use `prisma` which uses a [custom file extension](https://github.com/prisma/prisma#3-define-your-datamodel) for its data model definition (ex. `datamodel.prisma`).  The `*.prisma` also uses GraphQL SDL.  Based on [your recommendation](https://github.com/jparise/vim-graphql/issues/7) on another similar issue, I was able to get the syntax highlighting to work for `*.prisma` at https://github.com/serixscorpio/vim-graphql/commit/80b93f6604da99f61bf40be70ed19d0e6f232b5f.  If you think it makes sense to add built-in support for additional extensions, I can turn it into a PR.  Otherwise feel free to close this issue.  Thanks again!

**Comment by jparise** [comment]
Yes, I think it would be helpful to mention this in the `README.md`. Thanks!
