### ISSUE TITLE
June 2018 edition of the GraphQL specification update

### ISSUE THREAD

**Issue by ghost** [jparise/vim-graphql#36]
Hi,
any plans to update the plugin to https://github.com/graphql/graphql-spec/releases/tag/June2018

it's described as `the first edition to no longer be considered a "Draft RFC" to reflect its extensive use in production`

**Comment by jparise** [comment]
Thanks for the reminder!

I'll read through it in detail soon, but if there are any specific changes that you think I should make (aside from updating the documentation and examples), please point them out so I don't miss them.
