### ISSUE TITLE
Unkown function has_syntax_group

### ISSUE THREAD

**Issue by ZzCalvinzZ** [jparise/vim-graphql#45]
Super weird because `has_syntax_group` exists in `autoload/graphql.vim`

```
Error detected while processing /home/calvin/.config/nvim/bundle/vim-graphql/after/syntax/javascript/graphql.vim:
line   12:
E117: Unknown function: graphql#has_syntax_group
E15: Invalid expression: graphql#has_syntax_group('jsTemplateExpression')
Press ENTER or type command to continue
```

### Vim Version

```
NVIM v0.5.0-243-g251b20e53
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-e5e3117b-244c-4d55-aa5b-d0bdb2af417e

Features: +acl +iconv +tui

```

**Comment by jparise** [comment]
Could you try running through the same debugging steps we used in #35?

**Comment by ZzCalvinzZ** [comment]
K I figured it out. I also have the vim-polyglot plugin which loads this autoload file instead of the vim-graphql one:
https://github.com/sheerun/vim-polyglot/blob/master/autoload/graphql.vim

which is why I didn't get an error on the `graphql#javascript_tags` function.

I didn't realize they added to vim-polyglot.
All good here! And thanks for your work on this syntax support!

**Comment by jparise** [comment]
Great! I didn’t realize that project ships copies of other projects’ code. I don’t love that (for cases like this issue), but I’m glad you got this sorted out.

**Comment by RussBrown00** [comment]
I do have vim-polyglot installed, however adding graphql to the ignore list did not seem to fix anything.

```
let g:polyglot_disabled = ['markdown', 'graphql']
```

**Comment by jparise** [comment]
I don’t use `vim-polyglot`, but if you (temporarily) uninstall it, does the original problem go away?
