### ISSUE TITLE
linting support

### ISSUE THREAD

**Issue by AdrienLemaire** [jparise/vim-graphql#53]
This is probably a question and not a feature request.
I've just had a hard time debugging an issue that was due to a missing bracket on a directive in my .graphql file, and I wish a mark would have been auto-added by a linter to highlight the problem.
How do you configure vim-graphql to show syntax errors? Or does it need to be used with another plugin?

**Comment by jparise** [comment]
vim-graphql doesn't include a built-in linter so you'll need to use an external tool for that.

For example, it looks like [ALE](https://github.com/dense-analysis/ale) includes support for [gqlint](https://github.com/happylinks/gqlint), but I haven't tried it myself.

**Comment by AdrienLemaire** [comment]
Thanks! ALE doesn't seem to discover gqlint if we don't set the relative `./node_modules/.bin/` path to `$PATH` or installing gqlint system-wide. I'm also trying to avoid using ALE, having some conflicts with coc.nvim.
For the time being, I'll just run gqlint with `npm run lint` executed by `npm start`, this'll be good enough.
Thanks again for the hint :)
