### ISSUE TITLE
Breaks indentation if used with vim-jsx-pretty

### ISSUE THREAD

**Issue by sheerun** [jparise/vim-graphql#62]
This plugin breaks (disables) indentation for jsx code if vim-jsx-pretty is used. To reproduce please use following `~/.vimrc.test`:

```
call plug#begin()

set sw=2 ts=2

Plug 'pangloss/vim-javascript'
Plug 'MaxMEllon/vim-jsx-pretty'
Plug 'jparise/vim-graphql'


call plug#end()
```

And then open .js file with jsx with `vim -N -u ~/.vimrc.test component.js`

**Comment by sheerun** [comment]
Please see how vim-styled-components solved this: https://github.com/styled-components/vim-styled-components/blob/main/after/indent/javascript.vim#L138-L166

**Comment by jparise** [comment]
Thanks for the pointer! It looks like supporting the full "stack" of JS-adjacent plugins will be pretty involved so it will take me some time to put together a good test suite. Please add any important examples and test cases to this issue so I can include them. 

I'll try to pick this up over the weekend.

**Comment by sheerun** [comment]
` let l:result = cindent(v:lnum)` + recursion safeguard should be enough, no need to support stack of them
