### ISSUE TITLE
Emebeded highlighting fallbacks to string randomly in reason files

### ISSUE THREAD

**Issue by amiralies** [jparise/vim-graphql#76]
nvim 0.4.4
vim 8.2

After going to insert mode and back to normal mode it gets fixed. but when i move the cursor to query again it will broke.

https://user-images.githubusercontent.com/13261088/106646164-9e4ebe00-65a2-11eb-80f5-ce5e352f5547.mp4

**Comment by amiralies** [comment]
any idea why is this happening?

**Comment by jparise** [comment]
I'm afraid I haven't been able to reproduce this. I'm using https://github.com/jordwalke/vim-reasonml.

Are you using many other plugins? Is it possible one of them is interfering in some way?

**Comment by amiralies** [comment]
I'm using https://github.com/amiralies/vim-reason, but tried both jordwalke/vim-reasonml and reasonml-editor/vim-reason-plus and problem still occurs.

**Comment by jparise** [comment]
@amiralies Sorry for the delay!

I'm (finally) able to reproduce this. Now that I can, I'll see what I can do to get it fixed.

**Comment by jparise** [comment]
@amiralies #78 should hopefully fix things up for you.

**Comment by amiralies** [comment]
Fixed. Thanks!
