### ISSUE TITLE
graphql codegen support

### ISSUE THREAD

**Issue by zfogg** [jparise/vim-graphql#98]
i use https://github.com/dotansimha/graphql-code-generator and it gives me a function to call like

```javascript
gql(`
query MyQuery {
  myType {
    id
  }
}
`);
```

is there some way to get this plugin to syntax highlight a gql function call like this? i would love that

**Comment by jparise** [comment]
We don't support that library directly, but you should be able to add `# gql` (or `# graphql`) to the start of your template string to enable GraphQL syntax highlighting.

```js
gql(`# gql
query MyQuery {
  myType {
    id
  }
}
`);
```
